### ISSUE TITLE
Option to set or automatically detect the number of characters on a Mastodon server

### ISSUE THREAD

**Issue by jeroenpraat** [renatolond/mastodon-twitter-poster#366] opened 2020-04-26 20:43 UTC
Many Mastodon servers (forks, but also regular ones) have set their maximum character limit to a higher number. When a quoted retweet is crossposted and the total length goes _over_ the 500 characters (I guess this is because URL's are added and/or URL's are crossposted with their full length) the resulting toot on Mastodon is split between two toots (linked as a conversation). One toot with the added text and another with the retweet. 

My request is an option for the user to enter the number of characters toots can have on their server. So the toots are not split anymore. 

I know this can also be done automatically, cause most mobile apps do that. Probably @connyduck knows this.

**Comment by connyduck** [comment] 2020-04-27 05:45
Servers that have a higher limit usually return it in the `max_toot_chars` field of their `GET api/v1/instance`. See e.g. https://pleroma.site/api/v1/instance for an example.

**Comment by renatolond** [comment] 2020-04-27 09:36
This is a duplicate of #241, I've been working on that one to use the max_toot_chars from the instance, as @connyduck suggested :)

**Closed by renatolond** 2020-04-27 09:36 UTC
