### ISSUE TITLE
[Feature Request] remove tracking elements from URLs

### ISSUE THREAD

**Issue by Swrup** [renatolond/mastodon-twitter-poster#534] opened 2021-04-01 23:43 UTC
Many websites use tracking elements in the URL (UTM parameters).
They are not necessary for a website to be displayed or work correctly and can therefore be removed.
Many crossposts from twitter contains those trackers!

I propose to clean URLs before crossposting them.

This can be easily implemented.
The firefox add-on ClearURLs already does that and keep a list of UTM parameters to remove :
https://gitlab.com/KevinRoebert/ClearUrls

**Comment by renatolond** [comment] 2022-02-22 07:56
Hey, this is a duplicate of #119, but it's something I had my eye on for a while. Thanks for the ClearURLs link :)

**Closed** 2022-02-22 07:56 UTC
Labels: duplicate
