### ISSUE TITLE
Option to switch Twitter links to nitter or other instance-like

### ISSUE THREAD

**Issue by 1337god** [renatolond/mastodon-twitter-poster#490] opened 2021-01-20 17:12 UTC
Nitter is a free and open source alternative Twitter front-end focused on privacy. You can find the code here to even host it yourself: https://github.com/zedeus/nitter

A few good features from it:
- No JavaScript or ads
- All requests go through the backend, client never talks to Twitter
- Prevents Twitter from tracking your IP or JavaScript fingerprint
- Uses Twitter's unofficial API (no rate limits or developer account required)

**Comment by renatolond** [comment] 2021-01-20 18:36
Hi! This is a duplicate of #238, I'll close it, but don't hesitate to keep the conversation there!

**Closed by renatolond** 2021-01-20 18:36 UTC
