### ISSUE TITLE
Threads from Pleroma don't get posted

### ISSUE THREAD

**Issue by barudaret** [renatolond/mastodon-twitter-poster#104] opened 2018-06-01 20:13 UTC
If I respond to myself, making a thread, the thread doesn't get posted on Twitter, only the first toot does.  None of the replies show up.

**Comment by renatolond** [comment] 2018-06-29 16:05
Hm, I can't reproduce this. Either it was fixed by pleroma, or it was because you were replying to statuses created before you linked the crossposter to your account

**Closed by renatolond** 2018-06-29 16:05 UTC
