### ISSUE TITLE
Option to not crosspost toots with CW or with more than 200 characters to Twitter?

### ISSUE THREAD

**Issue by hellocam** [renatolond/mastodon-twitter-poster#67] opened 2018-01-17 22:42 UTC
Would this be at all possible?  CWs are usually a mess on Twitter and it sometimes becomes a problem when the toot is over 200 characters and/or if it's private.

**Comment by renatolond** [comment] 2018-01-18 09:46
Hi!
This a duplicate of #33 and #47, I'm going to close this one, but it is possible yes. Follow those ones to know when they're released :)

**Closed** 2018-01-18 09:47 UTC
