### ISSUE TITLE
improve the way how boosts are posted on Twitter

### ISSUE THREAD

**Issue by schiessle** [renatolond/mastodon-twitter-poster#117] opened 2018-07-08 17:38 UTC
Right now you can post boosts only as link on twitter. This makes boosts look really bad on Twitter, imho.

It would be nice to have similar options for forwarded toots as for forwarded retweets in addition to the existing option:

`Boosted @user@mastodon.social: Hello world`

and 

`Boosted @user@mastodon.social: Hello World <url>`

**Comment by renatolond** [comment] 2018-07-09 07:45
Hi! This a duplicate of #79, please take a look on the discussion over there on why this isn't implemented :)

Thanks for the suggestion!

**Closed by renatolond** 2018-07-09 07:45 UTC
