### ISSUE TITLE
Only crosspost with certain hashtag

### ISSUE THREAD

**Issue by jeroenpraat** [renatolond/mastodon-twitter-poster#91] opened 2018-04-22 20:57 UTC
Please add an option to only crosspost tweets (or toots the other way around) that contain certain (configurable) hashtags.

With this users can selectivity crosspost content.

**Comment by renatolond** [comment] 2018-04-23 08:30
Hi! :)
This is a duplicate of #60. Please follow it for news on this one :)

**Closed by renatolond** 2018-04-23 08:30 UTC
